spring:
  config:
    import: classpath:application-secret.yml

  application:
    name: portfolio

  datasource:
    url: jdbc:mysql://portfolio.sangwon97.com:3306/portfolio
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
